# Generated by Django 4.2.4 on 2023-08-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finch',
            name='habitation',
            field=models.TextField(max_length=300),
        ),
    ]
